source 'https://rubygems.org'
gem 'rails', '4.2.8'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'haml', '~> 4.0.5'
gem 'nifty-utils'
gem 'nilify_blanks', '~> 1.1.0'
gem 'authie'
gem 'annotate', '~> 2.6.5'
gem 'kaminari', '~> 0.16.1'
gem 'chronic', '~> 0.10.2'
gem 'dynamic_form'
gem 'bcrypt', '~> 3.1.7'
gem 'rails_env_config', group: :development
gem 'nifty-dialog'
gem 'puma'
